extract = 'total_dyn_inst: (\d+)'
#benchmarks = '../../bril/benchmarks/core/*.bril'
benchmarks = 'bril/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]
timeout = 100

[runs.trace]
pipeline = [
    "bril2json",
    "deno run trace.ts",
    "brili -p {args}",
]
timeout = 100