extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../bril/benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brilirs -p {args}",
]
timeout = 100

[runs.into_ssa]
pipeline = [
    "bril2json",
    "deno main.ts phi",
    "brilirs -p {args}",
]

[runs.out_of_ssa]
pipeline = [
    "bril2json",
    "deno main.ts",
    "brilirs -p {args}",
]


timeout = 100