extract = 'total_dyn_inst: (\d+)'
benchmarks = 'benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "node dce.js",
    "brili -p {args}",
]