[envs.dom]
command = "bril2json < {filename} | deno ../main.ts dom"
output."dom.json" = "-"

[envs.tree]
command = "bril2json < {filename} | deno ../main.ts tree"
output."tree.json" = "-"

[envs.front]
command = "bril2json < {filename} | deno ../main.ts front"
output."front.json" = "-"
